// Repository Tokens
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY'
export const NOTIFICATION_HISTORY_REPOSITORY = 'NOTIFICATION_HISTORY_REPOSITORY'
export const NOTIFICATION_STATS_REPOSITORY = 'NOTIFICATION_STATS_REPOSITORY'
export const NOTIFICATION_BATCH_REPOSITORY = 'NOTIFICATION_BATCH_REPOSITORY'

// External Service Tokens
export const EMAIL_CLIENT = 'EMAIL_CLIENT'
export const WHATSAPP_CLIENT = 'WHATSAPP_CLIENT'

// Database Token (kept for consistency)
export const NOTIFICATION_DATABASE = 'NOTIFICATION_DATABASE'

// Rate Limiter Configuration Tokens
export const RATE_LIMITER_MAX_REQUESTS = 'RATE_LIMITER_MAX_REQUESTS'
export const RATE_LIMITER_WINDOW_MS = 'RATE_LIMITER_WINDOW_MS'
