/**
 * Invisible marker appended to AI-generated messages
 * This prevents webhook loops by identifying messages sent by our AI
 * Using three Zero Width Spaces makes it virtually impossible for users to accidentally include this
 */
export const AI_MESSAGE_MARKER = '\u200B\u200B\u200B' // Three Zero Width Spaces

/**
 * Marks a message as AI-generated by appending invisible characters
 */
export function markAsAiMessage(content: string): string {
  return content + AI_MESSAGE_MARKER
}

/**
 * Checks if a message was generated by AI
 */
export function isAiMessage(content: string): boolean {
  return content.endsWith(AI_MESSAGE_MARKER)
}

/**
 * Removes AI marker from message content
 * Useful for displaying or storing clean content
 */
export function removeAiMarker(content: string): string {
  if (isAiMessage(content)) {
    return content.slice(0, -3) // Remove 3 characters
  }
  return content
}
